---
homebrew_url: https://raw.githubusercontent.com/Homebrew/install/master/install

taps:
  - homebrew/cask
  - homebrew/cask-fonts
  - wata727/tflint
  - borkdude/brew
  - wagoodman/dive
  - AdoptOpenJDK/openjdk

apps:
  - ansible
  - aria2
  - autoenv
  - autojump
  - aws-iam-authenticator
  - awscli
  - bat
  - caddy
  - cmake
  - exa
  - fd
  - fzf
  - gnu-sed
  - graphviz
  - git
  - git-delta
  - htop
  - hub
  - imagemagick
  - jq
  - lastpass-cli
  - libpq
  - mosh
  - nmap
  - packer
  - python
  - ripgrep
  - rustup
  - shellcheck
  - shfmt
  - terraform
  - terraform-inventory
  - tig
  - tldr
  - tor
  - tree
  - watchman
  - wget
  - xsv
  - yamllint
  - yq

  # Clojure
  - clojure
  - leiningen
  - boot-clj
  - clj-kondo

  # Docker
  - dive
  - kubernetes-cli

  # Golang
  - go
  - dep

  # Node
  - node
  - nvm
  - yarn

  #- neovim

  # Tmux
  - tmux
  - reattach-to-user-namespace

  # Zsh
  - zsh

  - xsv

  - httpie
  - ninja
  - hexyl

cask_apps:
  - adobe-acrobat-reader
  - alacritty
  - alfred
  - amazon-workspaces
  - anki
  - docker
  - font-fira-code
  - fork
  - google-backup-and-sync
  - google-chrome
  - google-cloud-sdk
  - kap
  - pgadmin4
  - postman
  - slack
  - spectacle
  - spotify
  - sublime-merge
  - teamviewer
  - telegram
  - tor-browser
  - transmission
  - tunnelblick
  - veracrypt
  - visual-studio-code
  - vlc
  - xmind
  - zoom

  # Java
  - adoptopenjdk8
  - visualvm
