---
apps:
  - gnupg
  - curl
  - clojure
  - rlwrap
  - make
  - cmake
  - ctags
  - fzf
  - dos2unix
  - git
  - graphviz
  - htop
  - imagemagick
  - jq
  - lastpass-cli
  - mosh
  - nmap
  - python
  - sshfs
  - tldr
  - tmux
  - tor
  - tree
  - wget
  - yamllint
  - unzip

  # Neovim
  - neovim
  - ripgrep

  # Node
  - nodejs
  - yarn
  - npm

  # Zsh
  - zsh

  # Docker
  - docker

  - lua5.1
  - golang-go

  - httpie

  - terraform
  - software-properties-common
  - google-cloud-cli
  - weechat
  - hexyl
  - ruby-full

cargo:
  - exa
  - bat
  - git-delta
  - xsv
  - code-minimap
