---
- name: Make sure golang is installed
  homebrew:
    name: go
    state: latest
    install_options: cross-compile-common

- name: Make sure dep is installed
  homebrew:
    name: dep
    state: latest

- name: Make sure golang workspace is exists
  file:
    path: ~/Projects/go-workspace
    state: directory

- name: Make sure go tools are installed
  shell: |
    go get -u -v github.com/ramya-rao-a/go-outline
    go get -u -v github.com/acroca/go-symbols
    go get -u -v github.com/nsf/gocode
    go get -u -v github.com/rogpeppe/godef
    go get -u -v golang.org/x/tools/cmd/godoc
    go get -u -v github.com/zmb3/gogetdoc
    go get -u -v github.com/golang/lint/golint
    go get -u -v github.com/fatih/gomodifytags
    go get -u -v golang.org/x/tools/cmd/gorename
    go get -u -v sourcegraph.com/sqs/goreturns
    go get -u -v golang.org/x/tools/cmd/goimports
    go get -u -v github.com/cweill/gotests/...
    go get -u -v golang.org/x/tools/cmd/guru
    go get -u -v github.com/josharian/impl
    go get -u -v github.com/haya14busa/goplay/cmd/goplay
    go get -u -v github.com/uudashr/gopkgs/cmd/gopkgs
    go get -u -v github.com/davidrjenni/reftools/cmd/fillstruct
    go get -u -v github.com/alecthomas/gometalinter
    gometalinter --install

- name: Install wego
  shell: |
    go get -u github.com/schachmat/wego
