---
- file:
    path: ~/.config
    state: directory

- file:
    path: ~/.config/lazygit
    state: directory

- name: Add config file
  template:
    src: templates/config.yml
    dest: ~/.config/lazygit/config.yml

- name: Install if ubuntu
  include: Ubuntu.yml
  when: ansible_distribution == 'Darwin'
